# Generated by Django 5.0.14 on 2026-09-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_videojuego_options_videojuego_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videojuego',
            options={},
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='videojuego',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='plataforma',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
