# Generated by Django 5.0.14 on 2026-10-06 06:59

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_videojuego_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videojuego',
            options={'ordering': ['titulo'], 'verbose_name': 'Videojuego', 'verbose_name_plural': 'Videojuegos'},
        ),
        migrations.AddField(
            model_name='videojuego',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='plataforma',
            field=models.CharField(choices=[('PS5', 'PlayStation 5'), ('PS4', 'PlayStation 4'), ('Xbox Series X', 'Xbox Series X/S'), ('Nintendo Switch', 'Nintendo Switch'), ('PC', 'PC Master Race'), ('Otro', 'Otra Plataforma')], default='PS5', max_length=50, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Precio (CLP)'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='titulo',
            field=models.CharField(help_text='Nombre completo del videojuego', max_length=100, verbose_name='Título del videojuego'),
        ),
    ]
