# Generated by Django 5.0.14 on 2026-10-06 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_videojuego_options_videojuego_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500000, message='El precio no puede superar los $500.000 CLP.')], verbose_name='Precio (CLP)'),
        ),
    ]
