# Generated by Django 6.1.1 on 2026-10-08 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_videojuego_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='precio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El precio debe ser al menos de $1 CLP.'), django.core.validators.MaxValueValidator(250000, message='El precio no puede superar los $250.000 CLP.')], verbose_name='Precio (CLP)'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo.'), django.core.validators.MaxValueValidator(100, message='El stock no puede superar las 100 unidades.')], verbose_name='Stock disponible'),
        ),
    ]
